name: expensetracker
description: "记账助储应用"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0
  provider: ^6.1.5+1
  path_provider: ^2.1.4
  csv: ^6.0.0
  uuid: ^4.5.3
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
