import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

class IconMapper {
  static IconData getIcon(String name) {
    switch (name) {
      // === 支出 ===
      case 'food':
        return MdiIcons.silverwareForkKnife;
      case 'shopping':
        return MdiIcons.shoppingOutline;
      case 'daily':
        return MdiIcons.paperRollOutline;
      case 'transport':
        return MdiIcons.bus;
      case 'vegetables':
        return MdiIcons.carrot;
      case 'fruit':
        return MdiIcons.fruitCherries;
      case 'snacks':
        return MdiIcons.cupcake;
      case 'entertainment':
        return MdiIcons.microphoneVariant;
      case 'communication':
        return MdiIcons.phoneInTalkOutline;
      case 'clothing':
        return MdiIcons.tshirtCrewOutline;
      case 'housing':
        return MdiIcons.homeOutline;
      case 'child':
        return MdiIcons.babyFaceOutline;
      case 'elders':
        return MdiIcons.faceManProfile;
      case 'social':
        return MdiIcons.chatOutline;
      case 'travel':
        return MdiIcons.airplane;
      case 'alcohol':
        return MdiIcons.glassWine;
      case 'digital':
        return MdiIcons.usb;
      case 'car':
        return MdiIcons.carOutline;
      case 'medical':
        return MdiIcons.medicalBag;
      case 'books':
        return MdiIcons.bookOutline;
      case 'study':
        return MdiIcons.schoolOutline;
      case 'gift-money':
        return MdiIcons.emailOutline;
      case 'gift':
        return MdiIcons.giftOutline;
      case 'office':
        return MdiIcons.briefcaseOutline;
      case 'repair':
        return MdiIcons.hammerWrench;
      case 'lottery':
        return MdiIcons.ticketOutline;
      case 'relatives':
        return MdiIcons.accountGroupOutline;
      case 'express':
        return MdiIcons.packageVariantClosed;
      case 'wish':
        return MdiIcons.heartOutline;
      case 'train':
        return MdiIcons.train;
      case 'phone-bill':
        return MdiIcons.cellphone;
      case 'utility':
        return MdiIcons.officeBuildingOutline;

      // === 收入 ===
      case 'salary':
        return MdiIcons.cashMultiple;
      case 'part-time':
        return MdiIcons.clockOutline;
      case 'investment':
        return MdiIcons.chartLine;
      case 'gift-money-income':
        return MdiIcons.emailOutline;
      case 'other':
        return MdiIcons.sackOutline;
      case 'lottery-income':
        return MdiIcons.ticketOutline;

      // === 系统图标/后备 ===
      case 'home-variant':
      case 'home-city':
        return MdiIcons.homeCity;
      case 'movie':
        return MdiIcons.movie;
      case 'hospital':
        return MdiIcons.hospital;
      case 'school':
        return MdiIcons.school;
      case 'heart':
        return MdiIcons.heart;
      case 'cog-outline':
        return MdiIcons.cogOutline;
      case 'plus':
        return MdiIcons.plus;
      case 'cash-multiple':
        return MdiIcons.cashMultiple;
      case 'format-list-bulleted':
        return MdiIcons.formatListBulleted;
      case 'chart-pie':
        return MdiIcons.chartPie;
      case 'account-outline':
        return MdiIcons.accountOutline;
      case 'account':
        return MdiIcons.account;
      case 'magnify':
        return MdiIcons.magnify;
      case 'chevron-down':
        return MdiIcons.chevronDown;
      case 'chevron-right':
        return MdiIcons.chevronRight;
      case 'signal':
        return MdiIcons.signal;
      case 'wifi':
        return MdiIcons.wifi;
      case 'battery':
        return MdiIcons.battery;
      case 'calendar-blank':
        return MdiIcons.calendarBlank;
      case 'pencil-outline':
        return MdiIcons.pencilOutline;
      case 'backspace-outline':
        return MdiIcons.backspaceOutline;
      case 'calendar-month-outline':
        return MdiIcons.calendarMonthOutline;
      case 'arrow-left':
        return MdiIcons.arrowLeft;
      case 'menu':
        return MdiIcons.menu;
      case 'file-export-outline':
        return MdiIcons.fileExportOutline;
      case 'cloud-sync-outline':
        return MdiIcons.cloudSyncOutline;
      case 'trash-can-outline':
        return MdiIcons.trashCanOutline;
      case 'palette-outline':
        return MdiIcons.paletteOutline;
      case 'bell-outline':
        return MdiIcons.bellOutline;
      case 'shield-lock-outline':
        return MdiIcons.shieldLockOutline;
      case 'information-outline':
        return MdiIcons.informationOutline;
      case 'star-outline':
        return MdiIcons.starOutline;
      default:
        return MdiIcons.fromString(name) ?? MdiIcons.helpCircleOutline;
    }
  }
}
